<a href="https://colab.research.google.com/github/AlyAbdulloh/Machine-Learning-semester5/blob/main/JS08/Tugas%20Praktikum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tugas Praktikum

- Lakukan klasifikasi pada data MNIST dengan menggunakan model ANN
- Anda diperbolehkan melakukan eksplorasi terhadap,
  - Metode pra pengolahan
  - Pemilihan fitur
  - Arsitektur ANN
  - Fungsi Aktiviasi
- ANN diimplementasikan dengan menggunakan tensorflow.
- DIKERJAKAN SECARA BERKELOMPOK
- JELASKAN HASIL YANG ANDA DAPATKAN,
  - AKURASI
  - CONFUSION MATRIX
  - KONFIGURASI MODEL --> MULAI DARI PRA PENGOLAHAN SAMPAI ARSITEKTUR ANN

### Langkah 1 - Import Library

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

### Langkah 2 - Pra-pengolahan data MNIST

In [2]:
# Pra-pengolahan data
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data() # load data MNIST dan split data

# ubah bentuk fitur menjadi vektor dan dinormalisasi
x_train = x_train.reshape(-1, 784).astype("float32") / 255.0
x_test = x_test.reshape(-1, 784).astype("float32") / 255.0

11490434/11490434 [==============================] - 1s 0us/step


### Langkkah 3 - Buat Arsitektur ANN

In [7]:
# Arsitektur ANN
# Terdiri dari 3 lapisan Dense dengan funsi aktivasi ReLU
ann = keras.Sequential(
    [
        layers.Dense(256, activation="relu"),
        layers.Dense(128, activation="relu"),
        layers.Dense(10),
    ]
)


### Langkah 4 - Buat Fugsi Aktivasi

In [8]:
# Fungsi aktivasi
ann.compile(
    optimizer=keras.optimizers.Adam(0.001),
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=["accuracy"],
)

### Langkah 5 - Latih Model ANN dan Lakukan Evaluasi Model

In [9]:
# Pelatihan model
# Model dilatih menggunakan data latih dengan batch size 32 dan epoch sebanyak 5 kali.
ann.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)

# Evaluasi model
# Model dievaluasi menggunakan data uji dan menghitung akurasi.
test_loss, test_acc = ann.evaluate(x_test, y_test, verbose=2)
print("Test accuracy:", test_acc)

Epoch 1/5
1875/1875 - 10s - loss: 0.2058 - accuracy: 0.9385 - 10s/epoch - 5ms/step
Epoch 2/5
1875/1875 - 9s - loss: 0.0871 - accuracy: 0.9729 - 9s/epoch - 5ms/step
Epoch 3/5
1875/1875 - 8s - loss: 0.0561 - accuracy: 0.9825 - 8s/epoch - 4ms/step
Epoch 4/5
1875/1875 - 11s - loss: 0.0441 - accuracy: 0.9858 - 11s/epoch - 6ms/step
Epoch 5/5
1875/1875 - 10s - loss: 0.0350 - accuracy: 0.9885 - 10s/epoch - 5ms/step
313/313 - 1s - loss: 0.0849 - accuracy: 0.9762 - 781ms/epoch - 2ms/step
Test accuracy: 0.9761999845504761


### Langkah 6 - Tampilkan Confusion Matrix

In [10]:
# Confusion matrix
# Confusion matrix dihitung menggunakan data uji dan prediksi model.
y_pred = ann.predict(x_test)
confusion_matrix = tf.math.confusion_matrix(y_test, tf.argmax(y_pred, axis=1))
print("Confusion matrix:\n", confusion_matrix)

313/313 [==============================] - 1s 2ms/step
Confusion matrix:
 tf.Tensor(
[[ 968    1    1    1    1    2    2    1    1    2]
 [   0 1124    1    0    0    2    6    0    1    1]
 [   4    2 1011    1    1    0    3    4    6    0]
 [   1    0    4  978    0    6    0    2    6   13]
 [   1    1    3    0  958    0    3    2    0   14]
 [   3    0    0    3    1  867   10    1    3    4]
 [  12    2    2    0    6    1  935    0    0    0]
 [   0   11    8    0    0    1    0  991    2   15]
 [   3    0    2    3    7    5    5    3  936   10]
 [   1    2    0    1    4    2    0    5    0  994]], shape=(10, 10), dtype=int32)
